[package]
name = "water_simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
